services:
  workspace:
    build:
      context: ./php-fpm
    container_name: work-container
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www/html/

  php-fpm:
    build:
      context: ./php-fpm
    container_name: backend-container
    ports:
      - "9000:9000"
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www/html/
    
  node:
    build:
      context: ./node
    container_name: frontend-container
    working_dir: /var/www/html
    ports:
      - "5173:5173"
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www/html

  nginx:
    image: nginx:alpine
    depends_on:
      - php-fpm
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:latest
    container_name: db-container
    depends_on:
      - php-fpm
    ports:
      - "3306:3306"
    env_file:
      - ./db/.env
    volumes:
      - ${DATA_PATH_HOST}:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/my.cnf

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    ports:
      - 1025:1025
      - 8025:8025
